### ISSUE TITLE
append method deprecated in pandas 2.0

### ISSUE THREAD

**Issue by BaldanMatt** [robertvsiii/community-simulator#12]
Dear developer,
I was using this simulator for quite a while because of trying to integrate this model-based simulator in a network inference pipeline. However, recently pandas has been upgraded and a few things have changed. One of them is the pd.DataFrame object method "append". It has been deprecated for a while, and now is removed. Substituted by pd.concat(). I suggest to update the repo, or add in the Readme.md file, specific version of dependencies, in order to give details to the user.

Command line ERROR:
  File "/***/***/.local/lib/python3.8/site-packages/community_simulator/__init__.py", line 257, in Propagate
    y_in = self.N.append(self.R).values
  File "/***/***/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

I'll also share a stackoverflow thread, where it is discussed about the "append" method being deprecated. It is also found in pandas documentation.
https://stackoverflow.com/questions/75956209/dataframe-object-has-no-attribute-append

Sincerely,
Matteo

**Comment by Jia-Xiu** [comment]
Hi Matteo, 
I am trying to run the simulator and got the same issue too. Did you solve the issue?
Best regards,
Xiu

**Comment by BaldanMatt** [comment]
The easy solution is using pandas version 1.5.3

Pandas 2.0 deprecated many implementations

**Comment by Wenping-Cui** [comment]
Have adjusted the code to fit the features of Pandas 3.0.
